In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
pd.options.display.float_format ='{:,.3f}'.format

In [5]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0        16.990 1.010  Female     No   Sun  Dinner     2
1        10.340 1.660    Male     No   Sun  Dinner     3
2        21.010 3.500    Male     No   Sun  Dinner     3
3        23.680 3.310    Male     No   Sun  Dinner     2
4        24.590 3.610  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239      29.030 5.920    Male     No   Sat  Dinner     3
240      27.180 2.000  Female    Yes   Sat  Dinner     2
241      22.670 2.000    Male    Yes   Sat  Dinner     2
242      17.820 1.750    Male     No   Sat  Dinner     2
243      18.780 3.000  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
df.describe(include='all')

        total_bill     tip   sex smoker  day    time    size
count      244.000 244.000   244    244  244     244 244.000
unique         NaN     NaN     2      2    4       2     NaN
top            NaN     NaN  Male     No  Sat  Dinner     NaN
freq           NaN     NaN   157    151   87     176     NaN
mean        19.786   2.998   NaN    NaN  NaN     NaN   2.570
std          8.902   1.384   NaN    NaN  NaN     NaN   0.951
min          3.070   1.000   NaN    NaN  NaN     NaN   1.000
25%         13.348   2.000   NaN    NaN  NaN     NaN   2.000
50%         17.795   2.900   NaN    NaN  NaN     NaN   2.000
75%         24.127   3.562   NaN    NaN  NaN     NaN   3.000
max         50.810  10.000   NaN    NaN  NaN     NaN   6.000

In [8]:
df['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [9]:
df['day'].value_counts() / df['day'].value_counts().sum() *100

Sat    35.656
Sun    31.148
Thur   25.410
Fri     7.787
Name: day, dtype: float64

In [10]:
df.groupby('sex').mean()

        total_bill   tip  size
sex
Male        20.744 3.090 2.631
Female      18.057 2.833 2.460

In [11]:
df['prct_tip'] = df['tip']/df['total_bill']
df

     total_bill   tip     sex smoker   day    time  size  prct_tip
0        16.990 1.010  Female     No   Sun  Dinner     2     0.059
1        10.340 1.660    Male     No   Sun  Dinner     3     0.161
2        21.010 3.500    Male     No   Sun  Dinner     3     0.167
3        23.680 3.310    Male     No   Sun  Dinner     2     0.140
4        24.590 3.610  Female     No   Sun  Dinner     4     0.147
..          ...   ...     ...    ...   ...     ...   ...       ...
239      29.030 5.920    Male     No   Sat  Dinner     3     0.204
240      27.180 2.000  Female    Yes   Sat  Dinner     2     0.074
241      22.670 2.000    Male    Yes   Sat  Dinner     2     0.088
242      17.820 1.750    Male     No   Sat  Dinner     2     0.098
243      18.780 3.000  Female     No  Thur  Dinner     2     0.160

[244 rows x 8 columns]

In [12]:
df.groupby('sex').mean()

        total_bill   tip  size  prct_tip
sex
Male        20.744 3.090 2.631     0.158
Female      18.057 2.833 2.460     0.166

In [13]:
df.groupby('sex').median()

        total_bill   tip  size  prct_tip
sex
Male        18.350 3.000 2.000     0.153
Female      16.400 2.750 2.000     0.156

In [14]:
df.groupby('sex')[['prct_tip']].describe()

       prct_tip
          count  mean   std   min   25%   50%   75%   max
sex
Male    157.000 0.158 0.065 0.036 0.121 0.153 0.186 0.710
Female   87.000 0.166 0.054 0.056 0.140 0.156 0.194 0.417

In [17]:
df.groupby('sex')[['total_bill','prct_tip']].describe()

       total_bill                                                prct_tip  \
            count   mean   std   min    25%    50%    75%    max    count
sex
Male      157.000 20.744 9.246 7.250 14.000 18.350 24.710 50.810  157.000
Female     87.000 18.057 8.009 3.070 12.750 16.400 21.520 44.300   87.000


        mean   std   min   25%   50%   75%   max
sex
Male   0.158 0.065 0.036 0.121 0.153 0.186 0.710
Female 0.166 0.054 0.056 0.140 0.156 0.194 0.417

In [22]:
def mean_eur2usd(x):
  return np.mean(x)*1.12

In [23]:
df.groupby('sex')[['total_bill','prct_tip']].apply(mean_eur2usd)

        total_bill  prct_tip
sex
Male        23.233     0.177
Female      20.224     0.186

In [20]:
df.groupby(['time','sex'])[['total_bill','prct_tip']].apply(mean_eur2usd)

               total_bill  prct_tip
time   sex
Lunch  Male        16.115     0.148
       Female      14.589     0.145
Dinner Male        19.162     0.139
       Female      17.155     0.151

In [21]:
df.groupby(['time','sex'])[['total_bill','prct_tip']].apply(lambda x: np.mean(x)*1.12)

               total_bill  prct_tip
time   sex
Lunch  Male        20.214     0.186
       Female      18.300     0.182
Dinner Male        24.037     0.174
       Female      21.519     0.190

In [25]:
df.groupby(['time','sex'])[['total_bill','prct_tip']].aggregate([np.mean, np.max])

              total_bill        prct_tip
                    mean   amax     mean  amax
time   sex
Lunch  Male       18.048 41.190    0.166 0.266
       Female     16.339 43.110    0.162 0.259
Dinner Male       21.461 50.810    0.155 0.710
       Female     19.213 44.300    0.169 0.417

In [26]:
df.groupby(['time','sex'])[['total_bill','prct_tip']].agg([np.mean, np.max])

              total_bill        prct_tip
                    mean   amax     mean  amax
time   sex
Lunch  Male       18.048 41.190    0.166 0.266
       Female     16.339 43.110    0.162 0.259
Dinner Male       21.461 50.810    0.155 0.710
       Female     19.213 44.300    0.169 0.417

In [28]:
dict_agg = {'tip': [min, max], 'total_bill': [np.mean, mean_eur2usd]}

In [30]:
df.groupby(['time','sex'])[['total_bill','tip']].agg(dict_agg)

                tip        total_bill
                min    max       mean mean_eur2usd
time   sex
Lunch  Male   1.440  6.700     18.048       20.214
       Female 1.250  5.170     16.339       18.300
Dinner Male   1.000 10.000     21.461       24.037
       Female 1.000  6.500     19.213       21.519

In [32]:
df['ones']=1
df

     total_bill   tip     sex smoker   day    time  size  prct_tip  ones
0        16.990 1.010  Female     No   Sun  Dinner     2     0.059     1
1        10.340 1.660    Male     No   Sun  Dinner     3     0.161     1
2        21.010 3.500    Male     No   Sun  Dinner     3     0.167     1
3        23.680 3.310    Male     No   Sun  Dinner     2     0.140     1
4        24.590 3.610  Female     No   Sun  Dinner     4     0.147     1
..          ...   ...     ...    ...   ...     ...   ...       ...   ...
239      29.030 5.920    Male     No   Sat  Dinner     3     0.204     1
240      27.180 2.000  Female    Yes   Sat  Dinner     2     0.074     1
241      22.670 2.000    Male    Yes   Sat  Dinner     2     0.088     1
242      17.820 1.750    Male     No   Sat  Dinner     2     0.098     1
243      18.780 3.000  Female     No  Thur  Dinner     2     0.160     1

[244 rows x 9 columns]

In [33]:
df_g = df.groupby(['sex', 'smoker'])[['ones']].sum()
df_g

               ones
sex    smoker
Male   Yes       60
       No        97
Female Yes       33
       No        54

In [34]:
df_g.groupby(level=0).apply(lambda x: x/x.sum() *100)

                ones
sex    smoker
Male   Yes    38.217
       No     61.783
Female Yes    37.931
       No     62.069

In [35]:
pd.cut(df['total_bill'], bins=3)

0       (3.022, 18.983]
1       (3.022, 18.983]
2      (18.983, 34.897]
3      (18.983, 34.897]
4      (18.983, 34.897]
             ...
239    (18.983, 34.897]
240    (18.983, 34.897]
241    (18.983, 34.897]
242     (3.022, 18.983]
243     (3.022, 18.983]
Name: total_bill, Length: 244, dtype: category
Categories (3, interval[float64, right]): [(3.022, 18.983] < (18.983, 34.897] < (34.897, 50.81]]

In [36]:
pd.cut(df['total_bill'], bins=3).value_counts()

(3.022, 18.983]     140
(18.983, 34.897]     88
(34.897, 50.81]      16
Name: total_bill, dtype: int64

In [39]:
pd.cut(df['total_bill'], bins=[3,18,35,60]).value_counts()

(3, 18]     127
(18, 35]    101
(35, 60]     16
Name: total_bill, dtype: int64

In [41]:
df['bin_total']= pd.cut(df['total_bill'], bins=[3,18,35,60])
df

,total_bill,tip,sex,smoker,day,time,size,prct_tip,ones,bin_total
0,16.990,1.010,Female,No,Sun,Dinner,2,0.059,1,"(3, 18]"
1,10.340,1.660,Male,No,Sun,Dinner,3,0.161,1,"(3, 18]"
2,21.010,3.500,Male,No,Sun,Dinner,3,0.167,1,"(18, 35]"
3,23.680,3.310,Male,No,Sun,Dinner,2,0.140,1,"(18, 35]"
4,24.590,3.610,Female,No,Sun,Dinner,4,0.147,1,"(18, 35]"
...,...,...,...,...,...,...,...,...,...,...
239,29.030,5.920,Male,No,Sat,Dinner,3,0.204,1,"(18, 35]"
240,27.180,2.000,Female,Yes,Sat,Dinner,2,0.074,1,"(18, 35]"
241,22.670,2.000,Male,Yes,Sat,Dinner,2,0.088,1,"(18, 35]"
242,17.820,1.750,Male,No,Sat,Dinner,2,0.098,1,"(3, 18]"
243,18.780,3.000,Female,No,Thur,Dinner,2,0.160,1,"(18, 35]"

In [43]:
df.groupby(['time', 'bin_total'])[['ones']].count().groupby(level=0).apply(lambda x: x/x.sum() *100)

                   ones
time   bin_total
Lunch  (3, 18]   66.176
       (18, 35]  30.882
       (35, 60]   2.941
Dinner (3, 18]   46.591
       (18, 35]  45.455
       (35, 60]   7.955

In [44]:
df

,total_bill,tip,sex,smoker,day,time,size,prct_tip,ones,bin_total
0,16.990,1.010,Female,No,Sun,Dinner,2,0.059,1,"(3, 18]"
1,10.340,1.660,Male,No,Sun,Dinner,3,0.161,1,"(3, 18]"
2,21.010,3.500,Male,No,Sun,Dinner,3,0.167,1,"(18, 35]"
3,23.680,3.310,Male,No,Sun,Dinner,2,0.140,1,"(18, 35]"
4,24.590,3.610,Female,No,Sun,Dinner,4,0.147,1,"(18, 35]"
...,...,...,...,...,...,...,...,...,...,...
239,29.030,5.920,Male,No,Sat,Dinner,3,0.204,1,"(18, 35]"
240,27.180,2.000,Female,Yes,Sat,Dinner,2,0.074,1,"(18, 35]"
241,22.670,2.000,Male,Yes,Sat,Dinner,2,0.088,1,"(18, 35]"
242,17.820,1.750,Male,No,Sat,Dinner,2,0.098,1,"(3, 18]"
243,18.780,3.000,Female,No,Thur,Dinner,2,0.160,1,"(18, 35]"

In [45]:
df.groupby(['sex', 'time'])[['total_bill']].mean()

               total_bill
sex    time
Male   Lunch       18.048
       Dinner      21.461
Female Lunch       16.339
       Dinner      19.213

In [47]:
df_gp= df.groupby(['sex', 'time'])[['total_bill']].mean().reset_index()
df_gp

      sex    time  total_bill
0    Male   Lunch      18.048
1    Male  Dinner      21.461
2  Female   Lunch      16.339
3  Female  Dinner      19.213

In [49]:
df_gp.pivot_table(values='total_bill', index= 'sex', columns='time')

time    Lunch  Dinner
sex
Male   18.048  21.461
Female 16.339  19.213

In [50]:
df.pivot_table(values='total_bill', index= 'sex', columns='time') # realiza elpromedio por defoult

time    Lunch  Dinner
sex
Male   18.048  21.461
Female 16.339  19.213

In [56]:
df.pivot_table(values='total_bill', index= 'sex', columns='time', aggfunc=np.median)

time    Lunch  Dinner
sex
Male   16.580  19.630
Female 13.420  17.190

In [57]:
df_pivot= df.pivot_table(values='total_bill', index= 'sex', columns='time', aggfunc=[np.median, np.std])
df_pivot

       median          std
time    Lunch Dinner Lunch Dinner
sex
Male   16.580 19.630 7.953  9.461
Female 13.420 17.190 7.501  8.202

In [59]:
df_pivot.unstack().reset_index()

  level_0    time     sex      0
0  median   Lunch    Male 16.580
1  median   Lunch  Female 13.420
2  median  Dinner    Male 19.630
3  median  Dinner  Female 17.190
4     std   Lunch    Male  7.953
5     std   Lunch  Female  7.501
6     std  Dinner    Male  9.461
7     std  Dinner  Female  8.202